safe: false # this is to enable plugins
port: 4000
baseurl: /
url: http://npiccolotto.com
name: "Nikolaus Piccolotto"
description: "a bit of everything"
host: npiccolotto.com
include: ['.htaccess', 'cv/*', 'projects/*']

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    kramdown
paginate:    10
relative_permalinks: true
permalink: /:year/:month/:title/
excerpt_separator: "\n\n"

rdiscount:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true
  enable_coderay: true

coderay:
  coderay_wrap: div
  coderay_line_numbers: ''
  coderay_line_numbers_start: 1
  coderay_tab_width: 2
  coderay_bold_every: 10
  coderay_css: style