baseURL = "https://npiccolotto.com/"
languageCode = "en-us"
title = "Nikolaus Piccolotto"
pygmentsUseClasses = true

summaryLength = 100

staticDir = ["static", "content/media"]
publishDir = "docs"
assetDir = "assets"

[permalinks]
  post = "/post/:slug/"
  project = "/project/:slug/"
  publication = "/publication/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"
