baseURL = "https://npiccolotto.com/"
languageCode = "en-us"
title = "Nikolaus Piccolotto"
pygmentsUseClasses = true

staticDir = ["static", "content/media"]

[permalinks]
  post = "/:slug/"
  project = "/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"
